spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 9
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
